version: '3'

services:
  springboot-docker-compose-app-container:
    image: organization-scheduling-pro-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/organization-scheduling-pro-app
    ports:
      - "8085:8085"