version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  organization-scheduling-pro:
    image: organization-scheduling-pro-app
    build: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes:
      - /data/organization-scheduling-pro-app
    ports:
      - "8085:8085"

#  If you use MySQL as Data storage,
#  also you need to change application.properties file configs
#  mysql:
#    container_name: v-mysql
#    image: mysql/mysql-server:5.7
#    environment:
#      MYSQL_DATABASE: test
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: '%'
#    ports:
#      - "3306:3306"
#    restart: always
